# Generated by Django 2.1.4 on 2018-12-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181216_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodespesa',
            name='remedio',
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='tipoDespesa',
            field=models.CharField(choices=[('a', 'Alimentação'), ('r', 'Roupas'), ('re', 'Remédio'), ('t', 'Transporte'), ('e', 'Educação'), ('o', 'Outros')], default='a', max_length=50),
        ),
    ]
