# Generated by Django 2.1.4 on 2018-12-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181216_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('ROUPA', 'Roupas'), ('REMEDIO', 'Remédio'), ('TRANSPORTE', 'Transporte'), ('EDUCACAO', 'Educação'), ('OUTROS', 'Outros')], max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoDespesa',
        ),
    ]
