# Generated by Django 2.1.4 on 2018-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181217_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO DE CREDITO', 'Cartão de Crédito'), ('CARTAO DE DEBITO', 'Cartão de Débito'), ('CARTAO CREDIARIO', 'Cartão Crediário'), ('CHEQUE', 'Cheque')], max_length=100),
        ),
    ]
